Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Description: >-
                 Add the frozen_string_literal comment to the top of files
                 to help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 120

MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 40

Metrics/ClassLength:
  CountComments: false
  Max: 200

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'bin/**'
    - 'db/**/*'
  TargetRubyVersion: 2.3
